### ISSUE TITLE
Question: How to use the library with sveltekit?

### ISSUE THREAD

**Issue by nooreldeensalah** [phiresky/sql.js-httpvfs#18]
Hi,

I wanted to know if it is possible to use Rollup.js as the module bundler instead of webpack? If so, I would like to see a minimal example of how it could be done, because I'm trying to use the library with sveltekit, and sveltekit seems to be using rollup.js/vite.js combination to do the bundling.

Regards,

**Comment by phiresky** [comment]
Sure, it should work just fine with rollup. You just need to make sure you make your bundler load sql.js-httpvfs/dist/sql.worker.js and sql.js-httpvfs/dist/sql-wasm.wasm as "assets" so it copies them into your output directory and gives you an URL. 

I don't have any experience with rollup, so I can't give you specific advice.

**Comment by nooreldeensalah** [comment]
I've found a workaround in a [repository](https://github.com/ric2b/static-search-page), the workaround was to copy was to copy `sqlite.worker.js` and `sql-wasm.wasm` from `node_modules` and put them in `static` and access them from there.

Credits to @ric2b.

I'll edit the issue title to make it more specific to what I was trying to do (which was to make it work with sveltekit) and then close it.

**Comment by GibreelAbdullah** [comment]
@nooreldeensalah sorry for reviving this. I am getting an error when trying to run this in sveltekit.

```
ReferenceError: Worker is not defined
    at t.createDbWorker (/home/alfi/Projects/Hadith-Hub/node_modules/sql.js-httpvfs/dist/index.js:377:35)
    at start (/home/alfi/Projects/Hadith-Hub/src/routes/lang/+page.svelte:19:24)
    at eval (/home/alfi/Projects/Hadith-Hub/src/routes/lang/+page.svelte:35:2)
    at Object.$$render (/home/alfi/Projects/Hadith-Hub/node_modules/svelte/internal/index.mjs:2042:22)
    at Object.default (/home/alfi/Projects/Hadith-Hub/.svelte-kit/generated/root.svelte:78:138)
    at Object.default (/home/alfi/Projects/Hadith-Hub/src/routes/+layout.svelte:204:44)
    at eval (/home/alfi/Projects/Hadith-Hub/node_modules/@skeletonlabs/skeleton/dist/components/AppShell/AppShell.svelte:70:140)
    at Object.$$render (/home/alfi/Projects/Hadith-Hub/node_modules/svelte/internal/index.mjs:2042:22)
    at eval (/home/alfi/Projects/Hadith-Hub/src/routes/+layout.svelte:152:88)
    at Object.$$render (/home/alfi/Projects/Hadith-Hub/node_modules/svelte/internal/index.mjs:2042:22)
```

I put the files `sql.worker.js` and `sql-wasm.wasm` in the static folder as done by ric2b in his repo.

**Comment by drozycki** [comment]
@GibreelAbdullah I was able to use this project with SvelteKit 2 by adding it to package.json dependencies and putting this in my svelte file:
```
onMount(async () => {
  const { createDbWorker } = await import('sql.js-httpvfs');
```
Using `onMount` ensures that this is imported only on the client. My SvelteKit app is configured for static site generation, not sure if you need to do anything else for SSR or SPA.

**Comment by GibreelAbdullah** [comment]
@drozycki Thanks!
