### ISSUE TITLE
Server crashes in the minimal example

### ISSUE THREAD

**Issue by chrisspen** [phiresky/sql.js-httpvfs#29]
All your steps for the [minimal example](https://github.com/phiresky/sql.js-httpvfs#minimal-example-from-scratch) work perfectly for me except:

    ./node_modules/.bin/http-server

For me, it initially launches correctly, but then crashes with the error:

    [Thu Apr 07 2022 22:28:06 GMT-0400 (Eastern Daylight Time)]  "GET /" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.83 Safari/537.36"
    _http_outgoing.js:470
        throw new ERR_HTTP_HEADERS_SENT('set');
        ^

    Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
        at ServerResponse.setHeader (_http_outgoing.js:470:11)
        at module.exports.ResponseStream.(anonymous function) [as setHeader] (/home/chris/git/asr/sqljs/node_modules/union/lib/response-stream.js:100:34)
        at Object.exports.(anonymous function) (/home/chris/git/asr/sqljs/node_modules/http-server/lib/core/status-handlers.js:57:7)
        at Readable.stream.on (/home/chris/git/asr/sqljs/node_modules/http-server/lib/core/index.js:339:22)
        at Readable.emit (events.js:198:13)
        at emitErrorNT (internal/streams/destroy.js:91:8)
        at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
        at process._tickCallback (internal/process/next_tick.js:63:19)

I'm unfamiliar with reading Node tracebacks.  It looks like it's receiving a request, but is having trouble writing the response. What's causing this?

**Comment by phiresky** [comment]
That might be a bug upstream with the [https://www.npmjs.com/package/http-server](http-server) library. I don't know why since it looks like this library was not updated since I used it. You can try using any other http server that supports range requests for now

**Comment by chrisspen** [comment]
Yeah, I think you're right. Looks like it was [reported here](https://github.com/http-party/http-server/issues/756) that version 14 no longer works at all, and a workaround is to revert to version 13.
