### ISSUE TITLE
Server crashes on starting

### ISSUE THREAD

**Issue by eafiontzi** [phiresky/sql.js-httpvfs#37]
Hello,

I am trying to use http-server with node version 12.14.0, when I start the server I get

```
$ http-server
Starting up http-server, serving ./

http-server version: 14.1.1

http-server settings:
CORS: disabled
Cache: 3600 seconds
Connection Timeout: 120 seconds
Directory Listings: visible
AutoIndex: visible
Serve GZIP Files: false
Serve Brotli Files: false
Default File Extension: none

Available on:
  http://153.89.58.106:8080
  http://192.168.1.12:8080
  http://127.0.0.1:8080
Hit CTRL-C to stop the server

events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: read EBADF
    at Pipe.onStreamRead (internal/stream_base_commons.js:201:27)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'EBADF',
  code: 'EBADF',
  syscall: 'read'
}
```

As seen [here](https://github.com/phiresky/sql.js-httpvfs/issues/29) I have tried installing the previous version 13.0.2 but the problem persists

```
$ http-server
Starting up http-server, serving ./

http-server settings:
CORS: disabled
Cache: 3600 seconds
Connection Timeout: 120 seconds
Directory Listings: visible
AutoIndex: visible
Serve GZIP Files: false
Serve Brotli Files: false
Default File Extension: none

Available on:
  http://153.89.58.106:8080
  http://192.168.1.12:8080
  http://127.0.0.1:8080
Hit CTRL-C to stop the server

events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: read EBADF
    at Pipe.onStreamRead (internal/stream_base_commons.js:201:27)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'EBADF',
  code: 'EBADF',
  syscall: 'read'
}
```

I also tried a different port from 8080, same results

Do you have any idea why this is happening or what can I do?

**Comment by phiresky** [comment]
try using node at least 16

Am Di., 9. Aug. 2022 um 11:36 Uhr schrieb Eleni Afiontzi <
***@***.***>:

**Comment by eafiontzi** [comment]
Sorry I opened the issue in the wrong repo, will close, thanks for the answer
