### ISSUE TITLE
Failing to init WASM with Node.js / Web Worker polyfill / type: `module`

### ISSUE THREAD

**Issue by mmomtchev** [phiresky/sql.js-httpvfs#46]
```
Error [TypeError]: Cannot set properties of undefined (setting 'exports')
    at webpack://sql.js-httpvfs/./sql.js/dist/sql-wasm.js:72:17903
    at new Promise (<anonymous>)
    at Object.default (webpack://sql.js-httpvfs/./sql.js/dist/sql-wasm.js:22:24)
    at init (webpack://sql.js-httpvfs/./src/sqlite.worker.ts:50:37)
    at Object.apply [as SplitFileHttpDatabase] (webpack://sql.js-httpvfs/./src/sqlite.worker.ts:109:26)
    at r (webpack://sql.js-httpvfs/./node_modules/comlink/dist/esm/comlink.mjs:94:48)
    at /home/mmom/src/ol-mbtiles/node_modules/web-worker/cjs/node.js:47:17
    at Array.forEach (<anonymous>)
    at dispatchEvent (/home/mmom/src/ol-mbtiles/node_modules/web-worker/cjs/node.js:45:10)
    at MessagePort.<anonymous> (/home/mmom/src/ol-mbtiles/node_modules/web-worker/cjs/node.js:171:25)
```

Caused by https://github.com/sql-js/sql.js/issues/406

**Comment by phiresky** [comment]
As mentioned in the Readme, this project was only ever made to be run in the browser, not Nodejs. It should be possible in theory, but probably not without other tweaks. I'm open to PRs to add nodejs support as long as they don't worsen the code base.

Other than that, for nodejs code I'd maybe try https://github.com/mlin/sqlite_web_vfs or https://github.com/psanford/sqlite3vfshttp as loadable extensions instead

**Comment by mmomtchev** [comment]
My Node.js support is needed only for unit-testing of the Web module, so I am ok with some rough edges and I don't want to use a binary extension.
